### ISSUE TITLE
`npm install --s react_native_mqtt` Missing mqttws31.js file

### ISSUE THREAD

**Issue by khjde1207** [Introvertuous/react_native_mqtt#21]
mkdir test 
cd test 
npm install --s react_native_mqtt
cd node_modules/react_native_mqtt/src
ls 
```
index.js
```
Missing mqttws31.js file

**Comment by Introvertuous** [comment]
sorry about that, dumb mistake, is fixed with `1.3.1`

**Comment by khjde1207** [comment]
Thank you!!
