### ISSUE TITLE
Red box error: Object is not a constructor (evaluating 'new Storage(options)')

### ISSUE THREAD

**Issue by ckwilhelm** [Introvertuous/react_native_mqtt#3]
I'm getting a show-stopping error in XCode and Android Studio after upgrading from 1.1.4 to 1.1.5. The red box error reads:

`Object is not a constructor (evaluating 'new Storage(options)')`

The version of react-native-storage included as a dependency is the same across versions, and the version of react-native we're using is also the same, so it doesn't appear that the problem comes from react-native's AsyncStorage. We're initializing react_native_mqtt exactly as shown in the README example. Error disappears after locking the version to 1.1.4, blowing away the node_modules directory and running npm install.

**Comment by Introvertuous** [comment]
sorry about that, just cut a new release that should work as expected (1.1.6).
